#!/bin/bash
echo FROM jelastic/nginxphp:$DOCKER_TAG > Dockerfile
echo LABEL deprecated=false nodeType=nginxphp-dockerized-old nodeTypeAlias=nginxphp-old >> Dockerfile
docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
